#!/bin/sh
# Wrapper script to run run gimp-2.9 installed together.
# with the necessary libraries at /opt/gimp-2.9
progname="$(basename $0)"
if [ $progname = 'gimp-git' ]; then
  progname=gimp-2.9
fi

PREFIX=/opt/gimp-2.9
export PATH=${PREFIX}/bin:PATH
export LD_LIBRARY_PATH=${PREFIX}/lib64:$LD_LIBRARY_PATH
export XDG_DATA_DIRS=$PREFIX/share:$XDG_DATA_DIRS
export ACLOCAL_FLAGS="-I $PREFIX/share/aclocal"
export PKG_CONFIG_PATH=$PREFIX/lib64/pkgconfig:$PKG_CONFIG_PATH
#export GIO_EXTRA_MODULES=/usr/lib64/gio/modules

${PREFIX}/bin/$progname -n$@
